---

- name: Commands All - firewall, selinux
  hosts: all
  ansible.builtin.shell:
    cmd: "{{ item }}"
  loop:
    - systemctl disable firewalld
    - systemctl stop firewalld

- name: Instaling Zabbix
  hosts: zabbix-server
  tasks:
    - name: Wget Repository Zabbix
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbisx-release-6.0-4.el8.noarch.rpm
        dest: /home/ansible/
        mode: '0777'

    - name: Install .rpm package
      ansible.builtin.yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm
        state: present 

    - name: Install Components Zabbbix
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - zabbix-server-mysql 
        - zabbix-web-mysql
        - zabbix-sql-scripts 
        - zabbix-nginx-conf
        - zabbix-agent
        - zabbix-selinux-policy

- name: MySQL -- Installl
  hosts: banco
  vars:
    user: repli
    password: Teste#20
    db_host1: <ip>
    db_host2: <ip>
  tasks:
    - name: Install Component DB - Mysql - Install
      yum:
        name: mysql-server
        state: latest

    - name: start service loop
      service:
        name: mysqld
        state: started
        enabled: true

    - name: Create a new database with name 'bobdata'
      community.mysql.mysql_db:
        name: zabbix
        state: present
        encoding: utf8mb4

    - name: Create database user with name 'replica' and password 'Teste#20' with replication database privileges
      community.mysql.mysql_user:
        name: replica
        password: Teste#20
        host: "{{ db_host2 }}"
        priv: '*.*:SUPER,REPLICATION CLIENT'
        state: present

    - name: Create database user with name 'zabbix' and password 'Teste#20' with ALL database privileges
      community.mysql.mysql_user:
        name: zabbix
        password: Teste#20
        host: "{{ db_host1 }}"
        priv: '*.*:ALL'
        state: present

    - name: creators = 1
      ansible.builtin.shell:
        cmd: "{{ item }}"
      loop:
        - mysql -u root --execute="set global log_bin_trust_function_creators = 1;"


- name: Configurações Zabbix - alteração do arquivo de conf, nginx e criação do schema no banco
  hosts: zabbix-server
  vars:
    banco: <mysql-node1>
    banco2: <mysql-node2>
  tasks:
    - name: Configurações Zabbix
      ansible.builtin.shell:
        cmd: "{{ item }}"
      loop:
        - sed -i s'/# DBPassword=/DBPassword=Julia#20/' /etc/zabbix/zabbix_server.conf
        - sed -i s'/# DBHost=localhost/DBHost=192.168.32.131/' /etc/zabbix/zabbix_server.conf
        - zcat /usr/share/zabbix-sql-scripts/mysql/server.sql.gz | mysql --default-character-set=utf8mb4 -h 192.168.32.131 -uzabbix -p'Teste#20' zabbix
        - mysql -u root --execute="set global log_bin_trust_function_creators = 0;"
        - sed -i s'/#        listen          8080;/        listen          80;/' /etc/nginx/conf.d/zabbix.conf
        - sed -i s'/#        server_name     example.com;/        server_name     192.168.32.131;/' /etc/nginx/conf.d/zabbix.conf

    - name: start service loop
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - zabbix-agent
        - zabbix-server
        - nginx
        - php-fpm





